version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: bbr-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bbr
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ../backend
      dockerfile: ../infra/docker/backend/Dockerfile
    container_name: bbr-backend
    volumes:
      - ../backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
      composer install &&
      php artisan key:generate &&
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/docker/frontend/Dockerfile
    container_name: bbr-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  scheduler:
    build:
      context: ../backend
      dockerfile: ../infra/docker/backend/Dockerfile
    container_name: bbr-scheduler
    restart: always
    volumes:
      - ../backend:/var/www
    depends_on:
      - backend
    command: >
      sh -c "
        # Wait for the backend to run migrations
        sleep 30 &&
        while [ true ]; do
          php /var/www/artisan schedule:run >> /dev/null 2>&1;
          sleep 60;
        done
      "

volumes:
  db_data:
